In [3]:
from scipy.stats import chi2_contingency
import numpy as np

In [7]:
# Females 0-2 hours
obs = np.array([[9372, 1519], [9009, 535]])
chi2_contingency(obs)

(390.558542691742,
 6.255788561520213e-87,
 1,
 array([[9796.30393932, 1094.69606068],
        [8584.69606068,  959.30393932]]))

In [8]:
# Females 2-4 hours
obs = np.array([[10312, 2018], [10033, 1914]])
chi2_contingency(obs)

(0.5094680579008262,
 0.4753692204476654,
 1,
 array([[10332.98389422,  1997.01610578],
        [10012.01610578,  1934.98389422]]))

In [9]:
# Males 0-2 hours
obs = np.array([[9338, 1293], [10088, 2008]])
chi2_contingency(obs)

(89.4066115569934,
 3.2146047110560275e-21,
 1,
 array([[ 9086.89250671,  1544.10749329],
        [10339.10749329,  1756.89250671]]))

In [10]:
# Males 2-4 hours
obs = np.array([[8669, 381], [9782, 1700]])
chi2_contingency(obs)

(622.6812371938724,
 1.9525395618717078e-137,
 1,
 array([[ 8132.74644457,   917.25355543],
        [10318.25355543,  1163.74644457]]))